apiVersion: v1
kind: Service
metadata:
  name: linkly
  labels:
    app.kubernetes.io/name: linkly
spec:
  selector:
    app.kubernetes.io/name: linkly
  ports:
    - name: http
      port: 8080
      targetPort: http
