# kind cluster — 1 control-plane + 3 worker. Çoklu node: drain / node-freeze deneyleri için.
# CNI kapalı → Calico kurulur (13'te NetworkPolicy için cluster'ı yeniden kurmamak).
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: ladder
networking:
  disableDefaultCNI: true
  podSubnet: 192.168.0.0/16
containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry]
      config_path = "/etc/containerd/certs.d"
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
        protocol: TCP
      - containerPort: 443
        hostPort: 443
        protocol: TCP
  - role: worker
  - role: worker
  - role: worker
